{'name': 'Odoo Website Product Share On Social Media',
'category': 'Website',
'sequence': 1,
'version': '18.0.1.1.1',
'author': 'Keypress IT Services',
'license': 'OPL-1',
'price': 9.99,
'currency': 'USD',
'website': 'https://www.keypress.co.in',
'summary': 'Share your website products on social media effortlessly with configurable settings and cross-platform dynamic sharing.',
'description': 'Easily share website products on social media with one click using Odoo Website Product Share On Social Media. Configure sharing options and enable dynamic sharing across platforms.',
'depends': ['website_sale', 'base'],
'data': ['templates/templates.xml', 'views/website.xml'],
'web.assets_frontend': [],
'images': ['static/description/banner.png'],
'installable': True,
'application': True,
'maintainer': 'Keypress IT Services',
'auto_install': False,}